spring.application.name=placement-tracker
server.port=8081
server.servlet.context-path=/api

# Database - PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/placement_tracker
spring.datasource.username=placement_user
spring.datasource.password=placement_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.show-sql=false
spring.jpa.open-in-view=false


# Connection Pool - HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-timeout=20000

# Hibernate Performance
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Elasticsearch
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.connection-timeout=5000
spring.elasticsearch.socket-timeout=60000



logging.level.root=INFO
logging.level.com.example.placement_tracker=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.security=TRACE
#logging.level.org.springframework.security=DEBUG

app.jwt.secret = your-super-secret-key-minimum-32-characters-long-for-security-4kT9#Lm2@Qx8!Pz7$Rw5&Ny1*Hb6^Vc3Zj0Df9Gs2Ka8Mp1X
app.jwt.expiration = 86400000
